### ISSUE TITLE
No value was found for the provided environment variable.

### ISSUE THREAD

**Issue by kmteam** [kyleherzog/AssemblyInfoReaderTask#19]
I'm trying to get the assembly number but it it seems variable isn't set...

```
    - task: AssembyInfoReader@2
      inputs:
        searchPattern: 'FooProject/Properties/AssemblyInfo.cs'
steps:
- script: echo $(AssemblyInfo.AssemblyVersion)

```

Any idea?
Thnks!

**Comment by kyleherzog** [comment]
I'm afraid I don't use YAML on my builds.  So, I'm not super familiar with it.  However, I just took a working build I have and selected the View YAML option.  It looks like this...
```
steps:
- task: kherzog.AssemblyInfoReader.assembly-info-reader-build-task.AssemblyInfoReader@2
  displayName: 'Generate variables $(PrimaryProjectFolder)\Properties\AssemblyInfo.cs'
  inputs:
    searchPattern: $(PrimaryProjectFolder)\Properties\AssemblyInfo.cs'
```

A couple thoughts here:
- You might need to change the type of slash in the search pattern.
- Not sure if the task name needs to be fully qualified.?
- If all else fails, the log output might give further clues.
